### ISSUE TITLE
На будущее - лучше в открытый доступ токен не выкладывать

### ISSUE THREAD

**Issue by DanaZL** [Snake-G/learn-homework-1#10]
https://github.com/Snake-G/learn-homework-1/blob/5bedb336889f3c21513d5368d8f1ac897c5a78e5/8_ephem_bot.py#L48

Обычно делать отдельный файл с паролями/токенами и в скриптах его импортируют (Сам файл добавляется в гитигнор и потому на гитхаб не попадает)

**Comment by Snake-G** [comment]
это прекрасно понимаю. тут обучение и этот ключ никому не нужен.
