### ISSUE TITLE
На будущее можно было бы сделать sum(список) :)

### ISSUE THREAD

**Issue by DanaZL** [Snake-G/learn-homework-1#8]
https://github.com/Snake-G/learn-homework-1/blob/5bedb336889f3c21513d5368d8f1ac897c5a78e5/3_for.py#L30

**Comment by Snake-G** [comment]
sum вместо вот этого? 
    for amount in number_of_sales:
        sales_amount += amount

если да - то затупил что-то... может из-за того, что задание на циклы было... и потому внимание на них концентрировал.

**Comment by DanaZL** [comment]
Да, все верно, вместо этого цикла. Это не ошибка - просто информация на будущее
